//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sicoju.desktop.WSJudicial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Caso", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class Caso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CasoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.DetalleCaso> DetalleCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> JuezIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SentenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CasoID {
            get {
                return this.CasoIDField;
            }
            set {
                if ((this.CasoIDField.Equals(value) != true)) {
                    this.CasoIDField = value;
                    this.RaisePropertyChanged("CasoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.DetalleCaso> DetalleCaso {
            get {
                return this.DetalleCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleCasoField, value) != true)) {
                    this.DetalleCasoField = value;
                    this.RaisePropertyChanged("DetalleCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierre {
            get {
                return this.FechaCierreField;
            }
            set {
                if ((this.FechaCierreField.Equals(value) != true)) {
                    this.FechaCierreField = value;
                    this.RaisePropertyChanged("FechaCierre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> JuezID {
            get {
                return this.JuezIDField;
            }
            set {
                if ((this.JuezIDField.Equals(value) != true)) {
                    this.JuezIDField = value;
                    this.RaisePropertyChanged("JuezID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sentencia {
            get {
                return this.SentenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.SentenciaField, value) != true)) {
                    this.SentenciaField = value;
                    this.RaisePropertyChanged("Sentencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.Caso> CasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RestablecerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.TipoUsuario TipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoUsuarioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioPerfil> UsuarioPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioTipoCaso> UsuarioTipoCasoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Caso> Caso {
            get {
                return this.CasoField;
            }
            set {
                if ((object.ReferenceEquals(this.CasoField, value) != true)) {
                    this.CasoField = value;
                    this.RaisePropertyChanged("Caso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Restablecer {
            get {
                return this.RestablecerField;
            }
            set {
                if ((this.RestablecerField.Equals(value) != true)) {
                    this.RestablecerField = value;
                    this.RaisePropertyChanged("Restablecer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.TipoUsuario TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoUsuarioID {
            get {
                return this.TipoUsuarioIDField;
            }
            set {
                if ((this.TipoUsuarioIDField.Equals(value) != true)) {
                    this.TipoUsuarioIDField = value;
                    this.RaisePropertyChanged("TipoUsuarioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioPerfil> UsuarioPerfil {
            get {
                return this.UsuarioPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioPerfilField, value) != true)) {
                    this.UsuarioPerfilField = value;
                    this.RaisePropertyChanged("UsuarioPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioTipoCaso> UsuarioTipoCaso {
            get {
                return this.UsuarioTipoCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioTipoCasoField, value) != true)) {
                    this.UsuarioTipoCasoField = value;
                    this.RaisePropertyChanged("UsuarioTipoCaso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCaso", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class DetalleCaso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Caso CasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CasoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DetalleCasoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Involucrado InvolucradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> InvolucradoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.TipoInvolucrado TipoInvolucradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoInvolucradoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Caso Caso {
            get {
                return this.CasoField;
            }
            set {
                if ((object.ReferenceEquals(this.CasoField, value) != true)) {
                    this.CasoField = value;
                    this.RaisePropertyChanged("Caso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CasoID {
            get {
                return this.CasoIDField;
            }
            set {
                if ((this.CasoIDField.Equals(value) != true)) {
                    this.CasoIDField = value;
                    this.RaisePropertyChanged("CasoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DetalleCasoID {
            get {
                return this.DetalleCasoIDField;
            }
            set {
                if ((this.DetalleCasoIDField.Equals(value) != true)) {
                    this.DetalleCasoIDField = value;
                    this.RaisePropertyChanged("DetalleCasoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Involucrado Involucrado {
            get {
                return this.InvolucradoField;
            }
            set {
                if ((object.ReferenceEquals(this.InvolucradoField, value) != true)) {
                    this.InvolucradoField = value;
                    this.RaisePropertyChanged("Involucrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InvolucradoID {
            get {
                return this.InvolucradoIDField;
            }
            set {
                if ((this.InvolucradoIDField.Equals(value) != true)) {
                    this.InvolucradoIDField = value;
                    this.RaisePropertyChanged("InvolucradoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.TipoInvolucrado TipoInvolucrado {
            get {
                return this.TipoInvolucradoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoInvolucradoField, value) != true)) {
                    this.TipoInvolucradoField = value;
                    this.RaisePropertyChanged("TipoInvolucrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoInvolucradoID {
            get {
                return this.TipoInvolucradoIDField;
            }
            set {
                if ((this.TipoInvolucradoIDField.Equals(value) != true)) {
                    this.TipoInvolucradoIDField = value;
                    this.RaisePropertyChanged("TipoInvolucradoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Involucrado", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class Involucrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.DetalleCaso> DetalleCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvolucradoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.DetalleCaso> DetalleCaso {
            get {
                return this.DetalleCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleCasoField, value) != true)) {
                    this.DetalleCasoField = value;
                    this.RaisePropertyChanged("DetalleCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvolucradoID {
            get {
                return this.InvolucradoIDField;
            }
            set {
                if ((this.InvolucradoIDField.Equals(value) != true)) {
                    this.InvolucradoIDField = value;
                    this.RaisePropertyChanged("InvolucradoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoInvolucrado", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoInvolucrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.DetalleCaso> DetalleCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoInvolucradoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.DetalleCaso> DetalleCaso {
            get {
                return this.DetalleCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleCasoField, value) != true)) {
                    this.DetalleCasoField = value;
                    this.RaisePropertyChanged("DetalleCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoInvolucradoID {
            get {
                return this.TipoInvolucradoIDField;
            }
            set {
                if ((this.TipoInvolucradoIDField.Equals(value) != true)) {
                    this.TipoInvolucradoIDField = value;
                    this.RaisePropertyChanged("TipoInvolucradoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuario", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoUsuarioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario> UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuarioID {
            get {
                return this.TipoUsuarioIDField;
            }
            set {
                if ((this.TipoUsuarioIDField.Equals(value) != true)) {
                    this.TipoUsuarioIDField = value;
                    this.RaisePropertyChanged("TipoUsuarioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario> Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioPerfil", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class UsuarioPerfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Perfil PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PerfilIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsuarioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioPerfilIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Perfil Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PerfilID {
            get {
                return this.PerfilIDField;
            }
            set {
                if ((this.PerfilIDField.Equals(value) != true)) {
                    this.PerfilIDField = value;
                    this.RaisePropertyChanged("PerfilID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioPerfilID {
            get {
                return this.UsuarioPerfilIDField;
            }
            set {
                if ((this.UsuarioPerfilIDField.Equals(value) != true)) {
                    this.UsuarioPerfilIDField = value;
                    this.RaisePropertyChanged("UsuarioPerfilID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioTipoCaso", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class UsuarioTipoCaso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.TipoCaso TipoCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoCasoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsuarioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioTipoCasoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.TipoCaso TipoCaso {
            get {
                return this.TipoCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCasoField, value) != true)) {
                    this.TipoCasoField = value;
                    this.RaisePropertyChanged("TipoCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoCasoID {
            get {
                return this.TipoCasoIDField;
            }
            set {
                if ((this.TipoCasoIDField.Equals(value) != true)) {
                    this.TipoCasoIDField = value;
                    this.RaisePropertyChanged("TipoCasoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsuarioID {
            get {
                return this.UsuarioIDField;
            }
            set {
                if ((this.UsuarioIDField.Equals(value) != true)) {
                    this.UsuarioIDField = value;
                    this.RaisePropertyChanged("UsuarioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioTipoCasoID {
            get {
                return this.UsuarioTipoCasoIDField;
            }
            set {
                if ((this.UsuarioTipoCasoIDField.Equals(value) != true)) {
                    this.UsuarioTipoCasoIDField = value;
                    this.RaisePropertyChanged("UsuarioTipoCasoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioPerfil> FormularioPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PerfilIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioPerfil> UsuarioPerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioPerfil> FormularioPerfil {
            get {
                return this.FormularioPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioPerfilField, value) != true)) {
                    this.FormularioPerfilField = value;
                    this.RaisePropertyChanged("FormularioPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PerfilID {
            get {
                return this.PerfilIDField;
            }
            set {
                if ((this.PerfilIDField.Equals(value) != true)) {
                    this.PerfilIDField = value;
                    this.RaisePropertyChanged("PerfilID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioPerfil> UsuarioPerfil {
            get {
                return this.UsuarioPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioPerfilField, value) != true)) {
                    this.UsuarioPerfilField = value;
                    this.RaisePropertyChanged("UsuarioPerfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormularioPerfil", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class FormularioPerfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Formulario FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FormularioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormularioPerfilIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sicoju.desktop.WSJudicial.Perfil PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PerfilIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Formulario Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FormularioID {
            get {
                return this.FormularioIDField;
            }
            set {
                if ((this.FormularioIDField.Equals(value) != true)) {
                    this.FormularioIDField = value;
                    this.RaisePropertyChanged("FormularioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormularioPerfilID {
            get {
                return this.FormularioPerfilIDField;
            }
            set {
                if ((this.FormularioPerfilIDField.Equals(value) != true)) {
                    this.FormularioPerfilIDField = value;
                    this.RaisePropertyChanged("FormularioPerfilID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sicoju.desktop.WSJudicial.Perfil Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PerfilID {
            get {
                return this.PerfilIDField;
            }
            set {
                if ((this.PerfilIDField.Equals(value) != true)) {
                    this.PerfilIDField = value;
                    this.RaisePropertyChanged("PerfilID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Formulario", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class Formulario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormularioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioPerfil> FormularioPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormularioID {
            get {
                return this.FormularioIDField;
            }
            set {
                if ((this.FormularioIDField.Equals(value) != true)) {
                    this.FormularioIDField = value;
                    this.RaisePropertyChanged("FormularioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioPerfil> FormularioPerfil {
            get {
                return this.FormularioPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioPerfilField, value) != true)) {
                    this.FormularioPerfilField = value;
                    this.RaisePropertyChanged("FormularioPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCaso", Namespace="http://schemas.datacontract.org/2004/07/sicoju.entities.Entities")]
    [System.SerializableAttribute()]
    public partial class TipoCaso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoCasoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioTipoCaso> UsuarioTipoCasoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoCasoID {
            get {
                return this.TipoCasoIDField;
            }
            set {
                if ((this.TipoCasoIDField.Equals(value) != true)) {
                    this.TipoCasoIDField = value;
                    this.RaisePropertyChanged("TipoCasoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.UsuarioTipoCaso> UsuarioTipoCaso {
            get {
                return this.UsuarioTipoCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioTipoCasoField, value) != true)) {
                    this.UsuarioTipoCasoField = value;
                    this.RaisePropertyChanged("UsuarioTipoCaso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormularioReporte", Namespace="http://schemas.datacontract.org/2004/07/sicoju.General")]
    [System.SerializableAttribute()]
    public partial class FormularioReporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfilReporte", Namespace="http://schemas.datacontract.org/2004/07/sicoju.General")]
    [System.SerializableAttribute()]
    public partial class PerfilReporte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSJudicial.IServicioJudicial")]
    public interface IServicioJudicial {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetCasosFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetCasosFiltroResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Caso> GetCasosFiltro(sicoju.desktop.WSJudicial.Caso pCaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetCasosFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetCasosFiltroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Caso>> GetCasosFiltroAsync(sicoju.desktop.WSJudicial.Caso pCaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetCaso", ReplyAction="http://tempuri.org/IServicioJudicial/GetCasoResponse")]
        sicoju.desktop.WSJudicial.Caso GetCaso(int pCasoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetCaso", ReplyAction="http://tempuri.org/IServicioJudicial/GetCasoResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Caso> GetCasoAsync(int pCasoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetInvolucrados", ReplyAction="http://tempuri.org/IServicioJudicial/GetInvolucradosResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Involucrado> GetInvolucrados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetInvolucrados", ReplyAction="http://tempuri.org/IServicioJudicial/GetInvolucradosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Involucrado>> GetInvolucradosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteDetalleCaso", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteDetalleCasoResponse")]
        void DeleteDetalleCaso(int pDetalleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteDetalleCaso", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteDetalleCasoResponse")]
        System.Threading.Tasks.Task DeleteDetalleCasoAsync(int pDetalleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveCaso", ReplyAction="http://tempuri.org/IServicioJudicial/SaveCasoResponse")]
        sicoju.desktop.WSJudicial.Caso SaveCaso(sicoju.desktop.WSJudicial.Caso pCaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveCaso", ReplyAction="http://tempuri.org/IServicioJudicial/SaveCasoResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Caso> SaveCasoAsync(sicoju.desktop.WSJudicial.Caso pCaso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetFormularios", ReplyAction="http://tempuri.org/IServicioJudicial/GetFormulariosResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario> GetFormularios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetFormularios", ReplyAction="http://tempuri.org/IServicioJudicial/GetFormulariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario>> GetFormulariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetFormulariosFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetFormulariosFiltroResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario> GetFormulariosFiltro(sicoju.desktop.WSJudicial.Formulario pFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetFormulariosFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetFormulariosFiltroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario>> GetFormulariosFiltroAsync(sicoju.desktop.WSJudicial.Formulario pFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetFormulariosPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/GetFormulariosPerfilResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioReporte> GetFormulariosPerfil(int pPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetFormulariosPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/GetFormulariosPerfilResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioReporte>> GetFormulariosPerfilAsync(int pPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteFormularioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteFormularioPerfilResponse")]
        void DeleteFormularioPerfil(int pFormularioPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteFormularioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteFormularioPerfilResponse")]
        System.Threading.Tasks.Task DeleteFormularioPerfilAsync(int pFormularioPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveFormularioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/SaveFormularioPerfilResponse")]
        void SaveFormularioPerfil(sicoju.desktop.WSJudicial.FormularioPerfil pFormularioPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveFormularioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/SaveFormularioPerfilResponse")]
        System.Threading.Tasks.Task SaveFormularioPerfilAsync(sicoju.desktop.WSJudicial.FormularioPerfil pFormularioPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveFormulario", ReplyAction="http://tempuri.org/IServicioJudicial/SaveFormularioResponse")]
        sicoju.desktop.WSJudicial.Formulario SaveFormulario(sicoju.desktop.WSJudicial.Formulario pFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveFormulario", ReplyAction="http://tempuri.org/IServicioJudicial/SaveFormularioResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Formulario> SaveFormularioAsync(sicoju.desktop.WSJudicial.Formulario pFormulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteFormulario", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteFormularioResponse")]
        void DeleteFormulario(int pFormularioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteFormulario", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteFormularioResponse")]
        System.Threading.Tasks.Task DeleteFormularioAsync(int pFormularioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/GetUsuarioResponse")]
        sicoju.desktop.WSJudicial.Usuario GetUsuario(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pCompleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/GetUsuarioResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Usuario> GetUsuarioAsync(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pCompleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/CambiarClave", ReplyAction="http://tempuri.org/IServicioJudicial/CambiarClaveResponse")]
        sicoju.desktop.WSJudicial.Usuario CambiarClave(sicoju.desktop.WSJudicial.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/CambiarClave", ReplyAction="http://tempuri.org/IServicioJudicial/CambiarClaveResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Usuario> CambiarClaveAsync(sicoju.desktop.WSJudicial.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/ValidarUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/ValidarUsuarioResponse")]
        string ValidarUsuario(sicoju.desktop.WSJudicial.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/ValidarUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<string> ValidarUsuarioAsync(sicoju.desktop.WSJudicial.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetUsuarios", ReplyAction="http://tempuri.org/IServicioJudicial/GetUsuariosResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario> GetUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetUsuarios", ReplyAction="http://tempuri.org/IServicioJudicial/GetUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario>> GetUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetUsuariosFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetUsuariosFiltroResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario> GetUsuariosFiltro(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pTodos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetUsuariosFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetUsuariosFiltroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario>> GetUsuariosFiltroAsync(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pTodos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteUsuarioResponse")]
        void DeleteUsuario(int pUsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteUsuarioResponse")]
        System.Threading.Tasks.Task DeleteUsuarioAsync(int pUsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/SaveUsuarioResponse")]
        sicoju.desktop.WSJudicial.Usuario SaveUsuario(sicoju.desktop.WSJudicial.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/SaveUsuarioResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Usuario> SaveUsuarioAsync(sicoju.desktop.WSJudicial.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetPerfiles", ReplyAction="http://tempuri.org/IServicioJudicial/GetPerfilesResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil> GetPerfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetPerfiles", ReplyAction="http://tempuri.org/IServicioJudicial/GetPerfilesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil>> GetPerfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetPerfilesFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetPerfilesFiltroResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil> GetPerfilesFiltro(sicoju.desktop.WSJudicial.Perfil pPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetPerfilesFiltro", ReplyAction="http://tempuri.org/IServicioJudicial/GetPerfilesFiltroResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil>> GetPerfilesFiltroAsync(sicoju.desktop.WSJudicial.Perfil pPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeletePerfil", ReplyAction="http://tempuri.org/IServicioJudicial/DeletePerfilResponse")]
        void DeletePerfil(int pPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeletePerfil", ReplyAction="http://tempuri.org/IServicioJudicial/DeletePerfilResponse")]
        System.Threading.Tasks.Task DeletePerfilAsync(int pPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SavePerfil", ReplyAction="http://tempuri.org/IServicioJudicial/SavePerfilResponse")]
        sicoju.desktop.WSJudicial.Perfil SavePerfil(sicoju.desktop.WSJudicial.Perfil pPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SavePerfil", ReplyAction="http://tempuri.org/IServicioJudicial/SavePerfilResponse")]
        System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Perfil> SavePerfilAsync(sicoju.desktop.WSJudicial.Perfil pPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetPerfilesUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/GetPerfilesUsuarioResponse")]
        System.Collections.Generic.List<sicoju.desktop.WSJudicial.PerfilReporte> GetPerfilesUsuario(int pUsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/GetPerfilesUsuario", ReplyAction="http://tempuri.org/IServicioJudicial/GetPerfilesUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.PerfilReporte>> GetPerfilesUsuarioAsync(int pUsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveUsuarioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/SaveUsuarioPerfilResponse")]
        void SaveUsuarioPerfil(sicoju.desktop.WSJudicial.UsuarioPerfil pUsuarioPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/SaveUsuarioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/SaveUsuarioPerfilResponse")]
        System.Threading.Tasks.Task SaveUsuarioPerfilAsync(sicoju.desktop.WSJudicial.UsuarioPerfil pUsuarioPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteUsuarioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteUsuarioPerfilResponse")]
        void DeleteUsuarioPerfil(int pUsuarioPerfilID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJudicial/DeleteUsuarioPerfil", ReplyAction="http://tempuri.org/IServicioJudicial/DeleteUsuarioPerfilResponse")]
        System.Threading.Tasks.Task DeleteUsuarioPerfilAsync(int pUsuarioPerfilID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioJudicialChannel : sicoju.desktop.WSJudicial.IServicioJudicial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioJudicialClient : System.ServiceModel.ClientBase<sicoju.desktop.WSJudicial.IServicioJudicial>, sicoju.desktop.WSJudicial.IServicioJudicial {
        
        public ServicioJudicialClient() {
        }
        
        public ServicioJudicialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioJudicialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJudicialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJudicialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Caso> GetCasosFiltro(sicoju.desktop.WSJudicial.Caso pCaso) {
            return base.Channel.GetCasosFiltro(pCaso);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Caso>> GetCasosFiltroAsync(sicoju.desktop.WSJudicial.Caso pCaso) {
            return base.Channel.GetCasosFiltroAsync(pCaso);
        }
        
        public sicoju.desktop.WSJudicial.Caso GetCaso(int pCasoID) {
            return base.Channel.GetCaso(pCasoID);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Caso> GetCasoAsync(int pCasoID) {
            return base.Channel.GetCasoAsync(pCasoID);
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Involucrado> GetInvolucrados() {
            return base.Channel.GetInvolucrados();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Involucrado>> GetInvolucradosAsync() {
            return base.Channel.GetInvolucradosAsync();
        }
        
        public void DeleteDetalleCaso(int pDetalleID) {
            base.Channel.DeleteDetalleCaso(pDetalleID);
        }
        
        public System.Threading.Tasks.Task DeleteDetalleCasoAsync(int pDetalleID) {
            return base.Channel.DeleteDetalleCasoAsync(pDetalleID);
        }
        
        public sicoju.desktop.WSJudicial.Caso SaveCaso(sicoju.desktop.WSJudicial.Caso pCaso) {
            return base.Channel.SaveCaso(pCaso);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Caso> SaveCasoAsync(sicoju.desktop.WSJudicial.Caso pCaso) {
            return base.Channel.SaveCasoAsync(pCaso);
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario> GetFormularios() {
            return base.Channel.GetFormularios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario>> GetFormulariosAsync() {
            return base.Channel.GetFormulariosAsync();
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario> GetFormulariosFiltro(sicoju.desktop.WSJudicial.Formulario pFormulario) {
            return base.Channel.GetFormulariosFiltro(pFormulario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Formulario>> GetFormulariosFiltroAsync(sicoju.desktop.WSJudicial.Formulario pFormulario) {
            return base.Channel.GetFormulariosFiltroAsync(pFormulario);
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioReporte> GetFormulariosPerfil(int pPerfilID) {
            return base.Channel.GetFormulariosPerfil(pPerfilID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.FormularioReporte>> GetFormulariosPerfilAsync(int pPerfilID) {
            return base.Channel.GetFormulariosPerfilAsync(pPerfilID);
        }
        
        public void DeleteFormularioPerfil(int pFormularioPerfilID) {
            base.Channel.DeleteFormularioPerfil(pFormularioPerfilID);
        }
        
        public System.Threading.Tasks.Task DeleteFormularioPerfilAsync(int pFormularioPerfilID) {
            return base.Channel.DeleteFormularioPerfilAsync(pFormularioPerfilID);
        }
        
        public void SaveFormularioPerfil(sicoju.desktop.WSJudicial.FormularioPerfil pFormularioPerfil) {
            base.Channel.SaveFormularioPerfil(pFormularioPerfil);
        }
        
        public System.Threading.Tasks.Task SaveFormularioPerfilAsync(sicoju.desktop.WSJudicial.FormularioPerfil pFormularioPerfil) {
            return base.Channel.SaveFormularioPerfilAsync(pFormularioPerfil);
        }
        
        public sicoju.desktop.WSJudicial.Formulario SaveFormulario(sicoju.desktop.WSJudicial.Formulario pFormulario) {
            return base.Channel.SaveFormulario(pFormulario);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Formulario> SaveFormularioAsync(sicoju.desktop.WSJudicial.Formulario pFormulario) {
            return base.Channel.SaveFormularioAsync(pFormulario);
        }
        
        public void DeleteFormulario(int pFormularioID) {
            base.Channel.DeleteFormulario(pFormularioID);
        }
        
        public System.Threading.Tasks.Task DeleteFormularioAsync(int pFormularioID) {
            return base.Channel.DeleteFormularioAsync(pFormularioID);
        }
        
        public sicoju.desktop.WSJudicial.Usuario GetUsuario(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pCompleto) {
            return base.Channel.GetUsuario(pUsuario, pCompleto);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Usuario> GetUsuarioAsync(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pCompleto) {
            return base.Channel.GetUsuarioAsync(pUsuario, pCompleto);
        }
        
        public sicoju.desktop.WSJudicial.Usuario CambiarClave(sicoju.desktop.WSJudicial.Usuario pUsuario) {
            return base.Channel.CambiarClave(pUsuario);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Usuario> CambiarClaveAsync(sicoju.desktop.WSJudicial.Usuario pUsuario) {
            return base.Channel.CambiarClaveAsync(pUsuario);
        }
        
        public string ValidarUsuario(sicoju.desktop.WSJudicial.Usuario pUsuario) {
            return base.Channel.ValidarUsuario(pUsuario);
        }
        
        public System.Threading.Tasks.Task<string> ValidarUsuarioAsync(sicoju.desktop.WSJudicial.Usuario pUsuario) {
            return base.Channel.ValidarUsuarioAsync(pUsuario);
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario> GetUsuarios() {
            return base.Channel.GetUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario>> GetUsuariosAsync() {
            return base.Channel.GetUsuariosAsync();
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario> GetUsuariosFiltro(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pTodos) {
            return base.Channel.GetUsuariosFiltro(pUsuario, pTodos);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Usuario>> GetUsuariosFiltroAsync(sicoju.desktop.WSJudicial.Usuario pUsuario, bool pTodos) {
            return base.Channel.GetUsuariosFiltroAsync(pUsuario, pTodos);
        }
        
        public void DeleteUsuario(int pUsuarioID) {
            base.Channel.DeleteUsuario(pUsuarioID);
        }
        
        public System.Threading.Tasks.Task DeleteUsuarioAsync(int pUsuarioID) {
            return base.Channel.DeleteUsuarioAsync(pUsuarioID);
        }
        
        public sicoju.desktop.WSJudicial.Usuario SaveUsuario(sicoju.desktop.WSJudicial.Usuario pUsuario) {
            return base.Channel.SaveUsuario(pUsuario);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Usuario> SaveUsuarioAsync(sicoju.desktop.WSJudicial.Usuario pUsuario) {
            return base.Channel.SaveUsuarioAsync(pUsuario);
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil> GetPerfiles() {
            return base.Channel.GetPerfiles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil>> GetPerfilesAsync() {
            return base.Channel.GetPerfilesAsync();
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil> GetPerfilesFiltro(sicoju.desktop.WSJudicial.Perfil pPerfil) {
            return base.Channel.GetPerfilesFiltro(pPerfil);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.Perfil>> GetPerfilesFiltroAsync(sicoju.desktop.WSJudicial.Perfil pPerfil) {
            return base.Channel.GetPerfilesFiltroAsync(pPerfil);
        }
        
        public void DeletePerfil(int pPerfilID) {
            base.Channel.DeletePerfil(pPerfilID);
        }
        
        public System.Threading.Tasks.Task DeletePerfilAsync(int pPerfilID) {
            return base.Channel.DeletePerfilAsync(pPerfilID);
        }
        
        public sicoju.desktop.WSJudicial.Perfil SavePerfil(sicoju.desktop.WSJudicial.Perfil pPerfil) {
            return base.Channel.SavePerfil(pPerfil);
        }
        
        public System.Threading.Tasks.Task<sicoju.desktop.WSJudicial.Perfil> SavePerfilAsync(sicoju.desktop.WSJudicial.Perfil pPerfil) {
            return base.Channel.SavePerfilAsync(pPerfil);
        }
        
        public System.Collections.Generic.List<sicoju.desktop.WSJudicial.PerfilReporte> GetPerfilesUsuario(int pUsuarioID) {
            return base.Channel.GetPerfilesUsuario(pUsuarioID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<sicoju.desktop.WSJudicial.PerfilReporte>> GetPerfilesUsuarioAsync(int pUsuarioID) {
            return base.Channel.GetPerfilesUsuarioAsync(pUsuarioID);
        }
        
        public void SaveUsuarioPerfil(sicoju.desktop.WSJudicial.UsuarioPerfil pUsuarioPerfil) {
            base.Channel.SaveUsuarioPerfil(pUsuarioPerfil);
        }
        
        public System.Threading.Tasks.Task SaveUsuarioPerfilAsync(sicoju.desktop.WSJudicial.UsuarioPerfil pUsuarioPerfil) {
            return base.Channel.SaveUsuarioPerfilAsync(pUsuarioPerfil);
        }
        
        public void DeleteUsuarioPerfil(int pUsuarioPerfilID) {
            base.Channel.DeleteUsuarioPerfil(pUsuarioPerfilID);
        }
        
        public System.Threading.Tasks.Task DeleteUsuarioPerfilAsync(int pUsuarioPerfilID) {
            return base.Channel.DeleteUsuarioPerfilAsync(pUsuarioPerfilID);
        }
    }
}
